version: '3.5'
services:
  nginx:
    image: nginx:alpine
    container_name: gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx
    networks:
      - service-hub

  nginxconfigmanager:
    image: jacksonbarreto/automation-hub-nginxconfigmanager:latest
    restart: always
    volumes:
      - ./nginx-config/sites-enabled:/app/sites-enabled
    networks:
      - service-hub

volumes:
  nginx-config:

networks:
  gate_network:
    driver: bridge
  service-hub:
    driver: bridge
    name: service-hub